"""Eventos oficiais do TraderIA_WDO."""

SYSTEM_STARTED = "SYSTEM_STARTED"
NEW_CANDLE = "NEW_CANDLE"
MARKET_DNA_UPDATED = "MARKET_DNA_UPDATED"
STRATEGY_SIGNAL_CREATED = "STRATEGY_SIGNAL_CREATED"
DECISION_CREATED = "DECISION_CREATED"
ORDER_CREATED = "ORDER_CREATED"
ORDER_CLOSED = "ORDER_CLOSED"
BACKTEST_FINISHED = "BACKTEST_FINISHED"
FEATURE_SNAPSHOT_CREATED = "FEATURE_SNAPSHOT_CREATED"
REGIME_ANALYSIS_CREATED = "REGIME_ANALYSIS_CREATED"
RESEARCH_ANALYSIS_CREATED = "RESEARCH_ANALYSIS_CREATED"
ALPHA001_SIGNAL_CREATED = "ALPHA001_SIGNAL_CREATED"
ALPHA001_VALIDATION_COMPLETED = "ALPHA001_VALIDATION_COMPLETED"

OFFICIAL_EVENTS = {
    SYSTEM_STARTED,
    NEW_CANDLE,
    MARKET_DNA_UPDATED,
    STRATEGY_SIGNAL_CREATED,
    DECISION_CREATED,
    ORDER_CREATED,
    ORDER_CLOSED,
    BACKTEST_FINISHED,
    FEATURE_SNAPSHOT_CREATED,
    REGIME_ANALYSIS_CREATED,
    RESEARCH_ANALYSIS_CREATED,
    ALPHA001_SIGNAL_CREATED,
    ALPHA001_VALIDATION_COMPLETED,
}
